services:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
    ports:
      - 3005:3005
    networks:
      - common-network
  mysql-container:
    image: mysql
    volumes:
      - /Tsk/english/mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: english
      MYSQL_ROOT_PASSWORD: 1413qqgmtskABC
    networks:
      - common-network
networks:
  common-network:
    driver: bridge
