NEST:
  PORT: 3005
  
TENCENT_CLOUD:
  SECRET_ID: AKIDGT3d3XhsAOjvtwqlkePxMYbYbYJGMZqA
  SECRET_KEY: MZlniXJwQo4DHtQ7iGpT0gH0ZzFPNAkB

JWT:
  SECRET: tang
  ACCESS_TOKEN_EXPIRES_TIME: 7d
  REFRESH_TOKEN_EXPIRES_TIME: 7d

LOG:
  ON: true

SWAGGER_ENABLE: true