NSET:
  PORT: 3000

MYSQL:
  DATABASE: accounting
  PORT: 3306
  HOST: rm-cn-x0r3mjikh0005e0o.rwlb.rds.aliyuncs.com
  USERNAME: root
  PASSWORD: 1413qqgmtskABC
  LOG_ON: true

REDIS:
  HOST: r-bp14a2o6s6rsc0ud8lpd.redis.rds.aliyuncs.com
  PORT: 6379
  DB: 0
  REGISTER_CODE : registerCode
  USERNAME : r-bp14a2o6s6rsc0ud8l
  PASSWORD : 1413qqgmtskABC

JWT:
  SECRET: tang
  ACCESS_TOKEN_EXPIRES_TIME: 7d
  REFRESH_TOKEN_EXPIRES_TIME: 7d

LOG:
  ON: true

SWAGGER_ENABLE: true