
MYSQL:
  DATABASE: english
  PORT: 3306
  HOST: 127.0.0.1
  USERNAME: root
  PASSWORD: "123456"
  LOG_ON: false

REDIS:
  HOST: r-bp14a2o6s6rsc0ud8lpd.redis.rds.aliyuncs.com
  PORT: 6379
  DB: 0
  REGISTER_CODE : registerCode
  USERNAME : r-bp14a2o6s6rsc0ud8l
  PASSWORD : 1413qqgmtskABC

JWT:
  SECRET: tang
  ACCESS_TOKEN_EXPIRES_TIME: 7d
  REFRESH_TOKEN_EXPIRES_TIME:  7d

LOG:
  ON: true

SWAGGER_ENABLE: true